basePath: /v1/api/
definitions:
  core.City:
    properties:
      geoname_id:
        type: integer
      name:
        type: string
    type: object
  core.CityRecord:
    properties:
      city:
        $ref: '#/definitions/core.City'
      continent:
        $ref: '#/definitions/core.Continent'
      country:
        $ref: '#/definitions/core.Country'
      location:
        $ref: '#/definitions/core.Location'
      postal_code:
        type: string
      subdivisions:
        items:
          $ref: '#/definitions/core.Subdivision'
        type: array
    type: object
  core.Continent:
    properties:
      code:
        type: string
      geoname_id:
        type: integer
      name:
        type: string
    type: object
  core.Country:
    properties:
      geoname_id:
        type: integer
      is_in_european_union:
        type: boolean
      iso_code:
        type: string
      name:
        type: string
    type: object
  core.CountryRecord:
    properties:
      continent:
        $ref: '#/definitions/core.Continent'
      country:
        $ref: '#/definitions/core.Country'
    type: object
  core.Location:
    properties:
      accuracy_radius:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      metro_code:
        type: integer
      time_zone:
        type: string
    type: object
  core.Subdivision:
    properties:
      geoname_id:
        type: integer
      iso_code:
        type: string
      name:
        type: string
    type: object
  v1.CityResponse:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/core.CityRecord'
      message:
        type: string
    type: object
  v1.CityResponseBatch:
    properties:
      code:
        type: string
      data:
        additionalProperties:
          $ref: '#/definitions/core.CityRecord'
        type: object
      message:
        type: string
    type: object
  v1.CountryResponse:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/core.CountryRecord'
      message:
        type: string
    type: object
  v1.CountryResponseBatch:
    properties:
      code:
        type: string
      data:
        additionalProperties:
          $ref: '#/definitions/core.CountryRecord'
        type: object
      message:
        type: string
    type: object
  v1.RequestBatch:
    properties:
      ip:
        items:
          type: string
        type: array
      lang:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple lbs server, currently only query location by IP feature
    is implemented
  termsOfService: https://github.com/nexuslab-dev/nexus-lbs
  title: Nexus LBS Api
  version: "1.0"
paths:
  /city/{ip}:
    get:
      description: query city by IP, with optional lang param
      parameters:
      - description: IP address
        in: path
        name: ip
        required: true
        type: string
      - description: response language
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CityResponse'
      summary: query city by IP
      tags:
      - lbs
  /city/batch:
    post:
      consumes:
      - application/json
      description: batch query city by IPs, with optional lang param
      parameters:
      - description: json payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/v1.RequestBatch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CityResponseBatch'
      summary: batch query city by IPs
      tags:
      - lbs
  /country/{ip}:
    get:
      description: query country by IP, with optional lang param
      parameters:
      - description: IP address
        in: path
        name: ip
        required: true
        type: string
      - description: response language
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CountryResponse'
      summary: query country by IP
      tags:
      - lbs
  /country/batch:
    post:
      consumes:
      - application/json
      description: batch query country by IPs, with optional lang param
      parameters:
      - description: json payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/v1.RequestBatch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CountryResponseBatch'
      summary: batch query country by IPs
      tags:
      - lbs
swagger: "2.0"
